### ISSUE TITLE
Bitcode Error

### ISSUE THREAD

**Issue by patrick-ogrady** [firebase/firechat-ios#6]
When building for ios9, I receive an error that libraries must be compiled with bitcode. Has there been any progress made on this?

**Comment by Romain-Lambert** [comment]
You just have to disable bitcode in the build settings and the app runs well.

**Comment by Divjyot** [comment]
Bit code is only generated during archiving!! So an archived framework will contain bitcode. Otherwise you have to disable the bitcode option.
